(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/uni-popup/uni-popup"],{"405c":function(t,n,i){},"6c69":function(t,n,i){"use strict";var e={"uni-transition":function(){return i.e("components/uni-transition/uni-transition").then(i.bind(null,"c2a5"))}},o=function(){var t=this,n=t.$createElement;t._self._c},s=[];i.d(n,"b",(function(){return o})),i.d(n,"c",(function(){return s})),i.d(n,"a",(function(){return e}))},c63c:function(t,n,i){"use strict";i.r(n);var e=i("d43c"),o=i.n(e);for(var s in e)"default"!==s&&function(t){i.d(n,t,(function(){return e[t]}))}(s);n["default"]=o.a},d0ee:function(t,n,i){"use strict";var e=i("405c"),o=i.n(e);o.a},d43c:function(t,n,i){"use strict";Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var e=function(){i.e("components/uni-transition/uni-transition").then(function(){return resolve(i("c2a5"))}.bind(null,i)).catch(i.oe)},o={name:"UniPopup",components:{uniTransition:e},props:{animation:{type:Boolean,default:!0},type:{type:String,default:"center"},maskClick:{type:Boolean,default:!0}},data:function(){return{ani:[],showPopup:!1,showTrans:!1,maskClass:{position:"fixed",bottom:0,top:0,left:0,right:0,backgroundColor:"rgba(0, 0, 0, 0.4)"},transClass:{position:"fixed",left:0,right:0}}},watch:{type:{handler:function(t){switch(this.type){case"top":this.ani=["slide-top"],this.transClass={position:"fixed",left:0,right:0};break;case"bottom":this.ani=["slide-bottom"],this.transClass={position:"fixed",left:0,right:0,bottom:0};break;case"center":this.ani=["zoom-out","fade"],this.transClass={position:"fixed",display:"flex",flexDirection:"column",bottom:0,left:0,right:0,top:0,justifyContent:"center",alignItems:"center"};break}},immediate:!0}},created:function(){},methods:{clear:function(t){t.stopPropagation()},open:function(){var t=this;this.showPopup=!0,this.$nextTick((function(){setTimeout((function(){t.showTrans=!0}),50)})),this.$emit("change",{show:!0})},close:function(t){var n=this;this.showTrans=!1,this.$nextTick((function(){clearTimeout(n.timer),n.timer=setTimeout((function(){n.$emit("change",{show:!1}),n.showPopup=!1}),300)}))},onTap:function(){this.maskClick&&this.close()}}};n.default=o},e409:function(t,n,i){"use strict";i.r(n);var e=i("6c69"),o=i("c63c");for(var s in o)"default"!==s&&function(t){i.d(n,t,(function(){return o[t]}))}(s);i("d0ee");var a,c=i("f0c5"),r=Object(c["a"])(o["default"],e["b"],e["c"],!1,null,"1c7d9d34",null,!1,e["a"],a);n["default"]=r.exports}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/uni-popup/uni-popup-create-component',
    {
        'components/uni-popup/uni-popup-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("e409"))
        })
    },
    [['components/uni-popup/uni-popup-create-component']]
]);
